<a href="https://colab.research.google.com/github/lokeshchowdary9220/N4si/blob/main/Lab_day_1_AML_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
1. #crating an array

import numpy as np
a = np.array([10,20,30,40,50])
print(a)

b = np.arange(5,11)
print(b)

c = np.linspace(1,10,5)
print(c)


[10 20 30 40 50]
[ 5  6  7  8  9 10]
[ 1.    3.25  5.5   7.75 10.  ]


In [10]:
2.#matrix operations
a= np.array([[5,4],[10,20]])

b= np.array([[10,20],[30,40]])

print(a+b)
print(a-b)
print(a*b)
print(a@b)

[[15 24]
 [40 60]]
[[ -5 -16]
 [-20 -20]]
[[ 50  80]
 [300 800]]
[[ 170  260]
 [ 700 1000]]


In [12]:
3. #Statastics

marks =np.array([20,30,50,80,90,94,99])

print(np.mean(marks))
print(np.max(marks))
print(np.min(marks))
print(np.std(marks))

66.14285714285714
99
20
30.0305966423226


In [17]:
#Assesment 1

rjy_weather =np.array([29,29,27,27,28,30,30,29,30,31,31,31,31,31,30,29,27,29,28,28,28,29,29,31,29,28,28,27,28,28])

print(f"Hottest day  Temperature : {np.max(rjy_weather)}")
print(f"Coldest day  Temperature: {np.min(rjy_weather)}")
print(f"Average Temperature : {np.mean(rjy_weather)}")
print(f"no of days above 35°C : {len(np.where(rjy_weather > 35)[0])}")

Hottest day  Temperature : 31
Coldest day  Tempwerature: 27
Average Temperature : 29.0
no of days above 35°C : 0
